sudo: false
language: node_js
node_js:
  - '0.12'
before_install: npm install -g grunt-cli
install: npm install
script: bash bin/deploy-gh-pages.sh
env:
  global:
    - GH_REF=github.com/lagden/growl.git
    - secure=hfV7es4P6in9OjeQ2YoaJ6lKdDnDulZUBcCWtOrvDij2Tf/CM7k6TBZ72p/YHBwqqen2ahHL3xefXpN5XkufmeIPBSsusYmaaIBpuvHsrfDnOOap2DqclwGPRnFIfHN4k5H7ZLuKr0E6aFwFc+Xd2RIu2vmr4tGAQie+Qctr3yf/uGxKWzn2U/J1TYUwhKbE7jjuN8Lj+XXHVWDlRLIrwEeImvFDFsrnARYJmJ1GrMKJDKhD5Jfn/4FDEBtroERWiVuaWYiBBU/TvlWIG9wtAotAZgonwMbTVWrv5b0xSBgujR5QGEzlX40kCgAHBKIFwKBltZhjiAxFUZHIp1l14xDiUUOKIMGNUsfAnkgkncFrZdPxyhluo9qMvWSLxOFsVeXvr2agfbNb2xzzqbkd/9uj3RZjQ0NLRN3kxR3KmNzgXJeqA7OYMe6vnAJ2RKCorCyXHgtUP6d/deyGhHRTVpkZhnoXK8b6kgwBkCbLlNF5vLX+MtCc8ALwT2eAZXIuhKnt832j8Pg+Nhs0YlwDKKylPscq5ExXwBLvtU/nIgvBY1tU3700oS6+aCvf3iba8XO3sdFgwwybO/2UGo3Daew3tOHHPilQnC+LZDFAMJd9/t2CdskSiEU3XSqdfFN9C6PHVC4PHUVIX+/3dRB/CbSlKnBUf4xLuBtNO7ybDHE=
